#!/usr/bin/env python3
"""
blender_ae_bridge.py — Blender Camera → After Effects JSX Bridge

Exports Blender camera animation, shot markers, and basic scene data into an
After Effects ExtendScript (JSX) file. Run the JSX in AE to recreate cameras
and composition markers.

Usage (outside Blender):
    python blender_ae_bridge.py export <project_slug>
    python blender_ae_bridge.py export <project_slug> --fps 24

Usage (inside Blender):
    blender --background --python blender_ae_bridge.py -- export <project_slug>

Output:
    05_PROJECTS/<project_slug>/07-compositing/ae_import.jsx
"""

import argparse
import json
import math
import os
import subprocess
import sys
from pathlib import Path

WORKSPACE_ROOT = Path(__file__).resolve().parent.parent
BLENDER_BINARY = "/Applications/Blender.app/Contents/MacOS/Blender"


def _load_json(path: Path) -> dict:
    if path.exists():
        return json.loads(path.read_text(encoding="utf-8"))
    return {}


JSX_TEMPLATE = '''// Auto-generated by blender_ae_bridge.py
// Project: {project_slug}
// Import this file in After Effects: File > Scripts > Run Script File

(function() {{
    var proj = app.project;
    if (!proj) {{
        app.newProject();
        proj = app.project;
    }}

    // Create folder structure
    var footageFolder = proj.items.addFolder("Footage");
    var compFolder = proj.items.addFolder("Comps");

    // Create master composition
    var masterComp = proj.items.addComp(
        "{project_slug}_MASTER",
        {width},
        {height},
        1.0,  // pixel aspect
        {duration},
        {fps}
    );
    masterComp.parentFolder = compFolder;

    // Add shot markers to master comp
{marker_script}

    // Create shot compositions and cameras
{shot_script}

    alert("Import complete: {shot_count} shots, {camera_count} cameras.");
}})();
'''


def _escape_js_string(s: str) -> str:
    return s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n')


class AEExporter:
    def __init__(self, project_slug: str, fps: float = 24.0):
        self.project_slug = project_slug
        self.fps = fps
        self.project_dir = WORKSPACE_ROOT / "05_PROJECTS" / project_slug
        self.layout_path = self.project_dir / "03-layout" / "layout.blend"
        self.output_dir = self.project_dir / "07-compositing"
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def export(self) -> dict:
        import bpy

        if not self.layout_path.exists():
            return {"status": "error", "message": f"Layout not found: {self.layout_path}"}

        bpy.ops.wm.open_mainfile(filepath=str(self.layout_path))
        scene = bpy.context.scene

        width = scene.render.resolution_x
        height = scene.render.resolution_y
        duration = scene.frame_end / scene.render.fps

        shots = []
        markers_jsx = []

        for obj in scene.objects:
            if obj.type != "CAMERA" or not obj.name.startswith("CAM_"):
                continue

            shot_id = obj.get("shot_id", obj.name[4:])
            frame_start = obj.get("layout_frame_start", 1)
            frame_end = obj.get("layout_frame_end", frame_start)
            shot_duration = (frame_end - frame_start + 1) / scene.render.fps

            # Collect keyframes
            cam_data = {
                "name": obj.name,
                "shot_id": shot_id,
                "lens_mm": obj.data.lens,
                "frames": [],
            }

            if obj.animation_data and obj.animation_data.action:
                for layer in obj.animation_data.action.layers:
                    for strip in layer.strips:
                        for cb in strip.channelbags:
                            for fc in cb.fcurves:
                                for kp in fc.keyframe_points:
                                    frame = int(kp.co[0])
                                    value = kp.co[1]
                                    # Only sample at frame boundaries
                                    if fc.data_path == "location":
                                        idx = len([f for f in cam_data["frames"] if f["frame"] == frame])
                                        if idx == 0:
                                            cam_data["frames"].append({"frame": frame, "loc": [0,0,0], "rot": [0,0,0]})
                                        cam_data["frames"][-1]["loc"][fc.array_index] = value
                                    elif fc.data_path == "rotation_euler":
                                        idx = len([f for f in cam_data["frames"] if f["frame"] == frame])
                                        if idx == 0:
                                            cam_data["frames"].append({"frame": frame, "loc": [0,0,0], "rot": [0,0,0]})
                                        cam_data["frames"][-1]["rot"][fc.array_index] = value
            else:
                # Static camera
                cam_data["frames"].append({
                    "frame": frame_start,
                    "loc": [obj.location.x, obj.location.y, obj.location.z],
                    "rot": [obj.rotation_euler.x, obj.rotation_euler.y, obj.rotation_euler.z],
                })

            # Sort frames and convert to AE coordinates
            cam_data["frames"].sort(key=lambda x: x["frame"])
            for f in cam_data["frames"]:
                # Blender Z-up to AE Y-up
                f["ae_pos"] = [f["loc"][0], -f["loc"][2], f["loc"][1]]
                f["ae_rot"] = [math.degrees(f["rot"][0]), math.degrees(f["rot"][2]), -math.degrees(f["rot"][1])]
                f["ae_time"] = (f["frame"] - frame_start) / scene.render.fps

            shots.append(cam_data)

            # Marker for master comp
            marker_time = frame_start / scene.render.fps
            markers_jsx.append(f'    masterComp.markerProperty.setValueAtTime({marker_time:.3f}, new MarkerValue("{shot_id}"));')

        # Build shot script
        shot_scripts = []
        for shot in shots:
            shot_id = shot["shot_id"]
            frames = shot["frames"]
            lens = shot["lens_mm"]

            jsx_lines = [
                f'    // Shot: {shot_id}',
                f'    var shotComp = proj.items.addComp("{shot_id}", {width}, {height}, 1.0, {duration}, {self.fps});',
                f'    shotComp.parentFolder = compFolder;',
                f'    var cam = shotComp.layers.addCamera("CAM_{shot_id}", [0, 0]);',
                f'    cam.property("Camera Options").property("Zoom").setValue({lens * 10:.1f});',
            ]

            for f in frames:
                t = f["ae_time"]
                p = f["ae_pos"]
                r = f["ae_rot"]
                jsx_lines.append(f'    cam.property("Transform").property("Position").setValueAtTime({t:.3f}, [{p[0]:.3f}, {p[1]:.3f}, {p[2]:.3f}]);')
                jsx_lines.append(f'    cam.property("Transform").property("X Rotation").setValueAtTime({t:.3f}, {r[0]:.3f});')
                jsx_lines.append(f'    cam.property("Transform").property("Y Rotation").setValueAtTime({t:.3f}, {r[1]:.3f});')
                jsx_lines.append(f'    cam.property("Transform").property("Z Rotation").setValueAtTime({t:.3f}, {r[2]:.3f});')

            shot_scripts.append("\n".join(jsx_lines))

        jsx = JSX_TEMPLATE.format(
            project_slug=self.project_slug,
            width=width,
            height=height,
            duration=duration,
            fps=self.fps,
            marker_script="\n".join(markers_jsx),
            shot_script="\n\n".join(shot_scripts),
            shot_count=len(shots),
            camera_count=len(shots),
        )

        output_path = self.output_dir / "ae_import.jsx"
        output_path.write_text(jsx, encoding="utf-8")

        return {
            "status": "ok",
            "project": self.project_slug,
            "output_path": str(output_path),
            "shots_exported": len(shots),
            "composition_width": width,
            "composition_height": height,
            "duration_seconds": round(duration, 2),
        }


# ── CLI ─────────────────────────────────────────────────────────────────────

def run_inside_blender():
    argv = sys.argv
    if "--" in argv:
        argv = argv[argv.index("--") + 1:]
    else:
        argv = []

    parser = argparse.ArgumentParser(description="Blender → After Effects Bridge")
    sub = parser.add_subparsers(dest="command", required=True)

    p_export = sub.add_parser("export", help="Export camera data to JSX")
    p_export.add_argument("project_slug", help="Project identifier")
    p_export.add_argument("--fps", type=float, default=24.0, help="Composition FPS")

    args = parser.parse_args(argv)

    if args.command == "export":
        exporter = AEExporter(args.project_slug, fps=args.fps)
        result = exporter.export()
        print(json.dumps(result, indent=2))


def run_outside_blender():
    parser = argparse.ArgumentParser(description="Blender → After Effects Bridge")
    sub = parser.add_subparsers(dest="command", required=True)

    p_export = sub.add_parser("export", help="Export camera data to JSX")
    p_export.add_argument("project_slug", help="Project identifier")
    p_export.add_argument("--fps", type=float, default=24.0, help="Composition FPS")

    args = parser.parse_args()
    script_path = Path(__file__).resolve()

    if args.command == "export":
        cmd = [
            BLENDER_BINARY,
            "--background",
            "--python", str(script_path),
            "--",
            "export", args.project_slug,
            "--fps", str(args.fps),
        ]
        print(f"🎬 Exporting AE bridge for {args.project_slug}...")
        subprocess.run(cmd, check=True)


def main():
    try:
        import bpy
        INSIDE_BLENDER = True
    except ImportError:
        INSIDE_BLENDER = False

    if INSIDE_BLENDER:
        run_inside_blender()
    else:
        run_outside_blender()


if __name__ == "__main__":
    main()
